/*
Copyright 2023 The Katanomi Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package obs

import (
	"io"
	"net/http"
)

// ObsClientInterface defines OBS client interface.
//
//go:generate mockgen -package=obs -destination=../testing/mock/github.com/huaweicloud/huaweicloud-sdk-go-obs/client_interface.go github.com/huaweicloud/huaweicloud-sdk-go-obs/obs ObsClientInterface
type ObsClientInterface interface {
	DeleteBucketCustomDomain(input *DeleteBucketCustomDomainInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetBucketCustomDomain(input *SetBucketCustomDomainInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketCustomDomain(bucketName string, extensions ...ExtensionOptions) (output *GetBucketCustomDomainOuput, err error)
	SetBucketMirrorBackToSource(input *SetBucketMirrorBackToSourceInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	DeleteBucketMirrorBackToSource(bucketName string, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketMirrorBackToSource(bucketName string, extensions ...ExtensionOptions) (output *GetBucketMirrorBackToSourceOuput, err error)
	ListBuckets(input *ListBucketsInput, extensions ...ExtensionOptions) (output *ListBucketsOutput, err error)
	CreateBucket(input *CreateBucketInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	DeleteBucket(bucketName string, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetBucketStoragePolicy(input *SetBucketStoragePolicyInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketStoragePolicy(bucketName string, extensions ...ExtensionOptions) (output *GetBucketStoragePolicyOutput, err error)
	SetBucketQuota(input *SetBucketQuotaInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketQuota(bucketName string, extensions ...ExtensionOptions) (output *GetBucketQuotaOutput, err error)
	HeadBucket(bucketName string, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketMetadata(input *GetBucketMetadataInput, extensions ...ExtensionOptions) (output *GetBucketMetadataOutput, err error)
	GetBucketFSStatus(input *GetBucketFSStatusInput, extensions ...ExtensionOptions) (output *GetBucketFSStatusOutput, err error)
	GetBucketStorageInfo(bucketName string, extensions ...ExtensionOptions) (output *GetBucketStorageInfoOutput, err error)
	GetBucketLocation(bucketName string, extensions ...ExtensionOptions) (output *GetBucketLocationOutput, err error)
	SetBucketAcl(input *SetBucketAclInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketAcl(bucketName string, extensions ...ExtensionOptions) (output *GetBucketAclOutput, err error)
	SetBucketPolicy(input *SetBucketPolicyInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketPolicy(bucketName string, extensions ...ExtensionOptions) (output *GetBucketPolicyOutput, err error)
	DeleteBucketPolicy(bucketName string, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetBucketCors(input *SetBucketCorsInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketCors(bucketName string, extensions ...ExtensionOptions) (output *GetBucketCorsOutput, err error)
	DeleteBucketCors(bucketName string, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetBucketVersioning(input *SetBucketVersioningInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketVersioning(bucketName string, extensions ...ExtensionOptions) (output *GetBucketVersioningOutput, err error)
	SetBucketWebsiteConfiguration(input *SetBucketWebsiteConfigurationInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketWebsiteConfiguration(bucketName string, extensions ...ExtensionOptions) (output *GetBucketWebsiteConfigurationOutput, err error)
	DeleteBucketWebsiteConfiguration(bucketName string, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetBucketLoggingConfiguration(input *SetBucketLoggingConfigurationInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketLoggingConfiguration(bucketName string, extensions ...ExtensionOptions) (output *GetBucketLoggingConfigurationOutput, err error)
	SetBucketLifecycleConfiguration(input *SetBucketLifecycleConfigurationInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketLifecycleConfiguration(bucketName string, extensions ...ExtensionOptions) (output *GetBucketLifecycleConfigurationOutput, err error)
	DeleteBucketLifecycleConfiguration(bucketName string, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetBucketEncryption(input *SetBucketEncryptionInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketEncryption(bucketName string, extensions ...ExtensionOptions) (output *GetBucketEncryptionOutput, err error)
	DeleteBucketEncryption(bucketName string, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetBucketTagging(input *SetBucketTaggingInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketTagging(bucketName string, extensions ...ExtensionOptions) (output *GetBucketTaggingOutput, err error)
	DeleteBucketTagging(bucketName string, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetBucketNotification(input *SetBucketNotificationInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketNotification(bucketName string, extensions ...ExtensionOptions) (output *GetBucketNotificationOutput, err error)
	SetBucketRequestPayment(input *SetBucketRequestPaymentInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketRequestPayment(bucketName string, extensions ...ExtensionOptions) (output *GetBucketRequestPaymentOutput, err error)
	SetBucketFetchPolicy(input *SetBucketFetchPolicyInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetBucketFetchPolicy(input *GetBucketFetchPolicyInput, extensions ...ExtensionOptions) (output *GetBucketFetchPolicyOutput, err error)
	DeleteBucketFetchPolicy(input *DeleteBucketFetchPolicyInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetBucketFetchJob(input *SetBucketFetchJobInput, extensions ...ExtensionOptions) (output *SetBucketFetchJobOutput, err error)
	GetBucketFetchJob(input *GetBucketFetchJobInput, extensions ...ExtensionOptions) (output *GetBucketFetchJobOutput, err error)
	UploadFile(input *UploadFileInput, extensions ...ExtensionOptions) (output *CompleteMultipartUploadOutput, err error)
	DownloadFile(input *DownloadFileInput, extensions ...ExtensionOptions) (output *GetObjectMetadataOutput, err error)
	ListObjects(input *ListObjectsInput, extensions ...ExtensionOptions) (output *ListObjectsOutput, err error)
	ListVersions(input *ListVersionsInput, extensions ...ExtensionOptions) (output *ListVersionsOutput, err error)
	HeadObject(input *HeadObjectInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	SetObjectMetadata(input *SetObjectMetadataInput, extensions ...ExtensionOptions) (output *SetObjectMetadataOutput, err error)
	DeleteObject(input *DeleteObjectInput, extensions ...ExtensionOptions) (output *DeleteObjectOutput, err error)
	DeleteObjects(input *DeleteObjectsInput, extensions ...ExtensionOptions) (output *DeleteObjectsOutput, err error)
	SetObjectAcl(input *SetObjectAclInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetObjectAcl(input *GetObjectAclInput, extensions ...ExtensionOptions) (output *GetObjectAclOutput, err error)
	RestoreObject(input *RestoreObjectInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	GetObjectMetadata(input *GetObjectMetadataInput, extensions ...ExtensionOptions) (output *GetObjectMetadataOutput, err error)
	GetAttribute(input *GetAttributeInput, extensions ...ExtensionOptions) (output *GetAttributeOutput, err error)
	GetObject(input *GetObjectInput, extensions ...ExtensionOptions) (output *GetObjectOutput, err error)
	PutObject(input *PutObjectInput, extensions ...ExtensionOptions) (output *PutObjectOutput, err error)
	NewFolder(input *NewFolderInput, extensions ...ExtensionOptions) (output *NewFolderOutput, err error)
	PutFile(input *PutFileInput, extensions ...ExtensionOptions) (output *PutObjectOutput, err error)
	CopyObject(input *CopyObjectInput, extensions ...ExtensionOptions) (output *CopyObjectOutput, err error)
	AppendObject(input *AppendObjectInput, extensions ...ExtensionOptions) (output *AppendObjectOutput, err error)
	ModifyObject(input *ModifyObjectInput, extensions ...ExtensionOptions) (output *ModifyObjectOutput, err error)
	RenameFile(input *RenameFileInput, extensions ...ExtensionOptions) (output *RenameFileOutput, err error)
	RenameFolder(input *RenameFolderInput, extensions ...ExtensionOptions) (output *RenameFolderOutput, err error)
	CreateSignedUrl(input *CreateSignedUrlInput, extensions ...ExtensionOptions) (output *CreateSignedUrlOutput, err error)
	ListMultipartUploads(input *ListMultipartUploadsInput, extensions ...ExtensionOptions) (output *ListMultipartUploadsOutput, err error)
	AbortMultipartUpload(input *AbortMultipartUploadInput, extensions ...ExtensionOptions) (output *BaseModel, err error)
	InitiateMultipartUpload(input *InitiateMultipartUploadInput, extensions ...ExtensionOptions) (output *InitiateMultipartUploadOutput, err error)
	UploadPart(_input *UploadPartInput, extensions ...ExtensionOptions) (output *UploadPartOutput, err error)
	CompleteMultipartUpload(input *CompleteMultipartUploadInput, extensions ...ExtensionOptions) (output *CompleteMultipartUploadOutput, err error)
	ListParts(input *ListPartsInput, extensions ...ExtensionOptions) (output *ListPartsOutput, err error)
	CopyPart(input *CopyPartInput, extensions ...ExtensionOptions) (output *CopyPartOutput, err error)
	CreateBrowserBasedSignature(input *CreateBrowserBasedSignatureInput) (output *CreateBrowserBasedSignatureOutput, err error)
	ListBucketsWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *ListBucketsOutput, err error)
	CreateBucketWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	DeleteBucketWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	SetBucketStoragePolicyWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketStoragePolicyWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketStoragePolicyOutput, err error)
	ListObjectsWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *ListObjectsOutput, err error)
	ListVersionsWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *ListVersionsOutput, err error)
	ListMultipartUploadsWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *ListMultipartUploadsOutput, err error)
	SetBucketQuotaWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketQuotaWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketQuotaOutput, err error)
	HeadBucketWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	HeadObjectWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	GetBucketMetadataWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketMetadataOutput, err error)
	GetBucketStorageInfoWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketStorageInfoOutput, err error)
	GetBucketLocationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketLocationOutput, err error)
	SetBucketAclWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketAclWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketAclOutput, err error)
	SetBucketPolicyWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketPolicyWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketPolicyOutput, err error)
	DeleteBucketPolicyWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	SetBucketCorsWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketCorsWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketCorsOutput, err error)
	DeleteBucketCorsWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	SetBucketVersioningWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketVersioningWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketVersioningOutput, err error)
	SetBucketWebsiteConfigurationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketWebsiteConfigurationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketWebsiteConfigurationOutput, err error)
	DeleteBucketWebsiteConfigurationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	SetBucketLoggingConfigurationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketLoggingConfigurationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketLoggingConfigurationOutput, err error)
	SetBucketLifecycleConfigurationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketLifecycleConfigurationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketLifecycleConfigurationOutput, err error)
	DeleteBucketLifecycleConfigurationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	SetBucketTaggingWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketTaggingWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketTaggingOutput, err error)
	DeleteBucketTaggingWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	SetBucketNotificationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketNotificationWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketNotificationOutput, err error)
	DeleteObjectWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *DeleteObjectOutput, err error)
	DeleteObjectsWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *DeleteObjectsOutput, err error)
	SetObjectAclWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetObjectAclWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetObjectAclOutput, err error)
	RestoreObjectWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetObjectMetadataWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetObjectMetadataOutput, err error)
	GetObjectWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetObjectOutput, err error)
	PutObjectWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *PutObjectOutput, err error)
	PutFileWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, sourceFile string) (output *PutObjectOutput, err error)
	CopyObjectWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *CopyObjectOutput, err error)
	AbortMultipartUploadWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	InitiateMultipartUploadWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *InitiateMultipartUploadOutput, err error)
	UploadPartWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *UploadPartOutput, err error)
	CompleteMultipartUploadWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *CompleteMultipartUploadOutput, err error)
	ListPartsWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *ListPartsOutput, err error)
	CopyPartWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *CopyPartOutput, err error)
	SetBucketRequestPaymentWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketRequestPaymentWithSignedUrl(signedUrl string, actualSignedRequestHeaders http.Header) (output *GetBucketRequestPaymentOutput, err error)
	SetBucketEncryptionWithSignedURL(signedURL string, actualSignedRequestHeaders http.Header, data io.Reader) (output *BaseModel, err error)
	GetBucketEncryptionWithSignedURL(signedURL string, actualSignedRequestHeaders http.Header) (output *GetBucketEncryptionOutput, err error)
	DeleteBucketEncryptionWithSignedURL(signedURL string, actualSignedRequestHeaders http.Header) (output *BaseModel, err error)
	AppendObjectWithSignedURL(signedURL string, actualSignedRequestHeaders http.Header, data io.Reader) (output *AppendObjectOutput, err error)
	ModifyObjectWithSignedURL(signedURL string, actualSignedRequestHeaders http.Header, data io.Reader) (output *ModifyObjectOutput, err error)
}
